### PR TITLE
Changed configuration to use ServerPropertiesService

### PR DESCRIPTION
**Pull request by govertbuijs**
Major refactoring and cleanup

### CODE REVIEW

**Comment by jecollins** [comment]
The inversion of the config structure really changes how you view a config. You can see how all the time-series compare, but you cannot get an overall view of any individual model. I wonder if it might make sense to split the config into one file/model?

**Comment by jecollins** [comment]
I pulled in the changes (to a branch) and installed common and the server. When I run the server using mvn -Pweb in the server-distribution package, I get an exception:

```
java.lang.ArrayIndexOutOfBoundsException: 20604
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:898)
```

and so on for many pages.

**Comment by jecollins** [comment]
Possible clue, from boot config:

```
4131 ERROR config.Configurator: no configurable property named entityType on class org.powertac.factoredcustomer.CustomerStructure
```

**Comment by jecollins** [comment]
Here's another anomaly:

```
4142 DEBUG config.Configurator: ConfigurableValue method found on setDailySkew
4142 DEBUG config.Configurator: removing 'set' from setDailySkew
4142 DEBUG config.Configurator: getter name getDailySkew
4142 WARN  config.Configurator: Type mismatch: cannot use default value ([D) for  (java.util.List)
```

**Comment by govertbuijs** [comment]
I'll have a look at the errors it tomorrow. 

Yes, one file per model makes more sense.

**Comment by jecollins** [comment]
There's an ERROR in the log:

```
4192 DEBUG config.Configurator: Configuring property id
4192 ERROR config.Configurator: no configurable property named id on class org.powertac.factoredcustomer.DefaultCapacityBundle
```

This is in used in MedicalCenter and WindmillCoop. If the names are unique, can we just drop the id field?

**Comment by jecollins** [comment]
Additional ERROR entries:

```
4202 ERROR config.Configurator: No getter method getYh for org.powertac.factoredcustomer.TimeseriesGenerator
4203 ERROR config.Configurator: No getter method getYd for org.powertac.factoredcustomer.TimeseriesGenerator
4203 ERROR config.Configurator: No getter method getRefSeries for org.powertac.factoredcustomer.TimeseriesGenerator
```

**Comment by jecollins** [comment]
Given the errors and warnings, I am going to reject this pull request and wait for another. I hope that makes sense.

**Pull request merged**
